// Generated by `wit-bindgen` 0.51.0. DO NOT EDIT!
#include "types_test.h"
#include <stdlib.h>
#include <string.h>

// Exported Functions from `local:types-test/primitives`






__attribute__((__weak__, __export_name__("cabi_post_local:types-test/primitives#echo-string")))
void __wasm_export_exports_local_types_test_primitives_echo_string_post_return(uint8_t * arg0) {
  if ((*((size_t*) (arg0 + sizeof(void*)))) > 0) {
    free(*((uint8_t **) (arg0 + 0)));
  }
}

// Exported Functions from `local:types-test/enums`


__attribute__((__weak__, __export_name__("cabi_post_local:types-test/enums#color-name")))
void __wasm_export_exports_local_types_test_enums_color_name_post_return(uint8_t * arg0) {
  if ((*((size_t*) (arg0 + sizeof(void*)))) > 0) {
    free(*((uint8_t **) (arg0 + 0)));
  }
}

// Exported Functions from `local:types-test/flags-test`




// Exported Functions from `local:types-test/containers`


__attribute__((__weak__, __export_name__("cabi_post_local:types-test/containers#echo-list-s64")))
void __wasm_export_exports_local_types_test_containers_echo_list_s64_post_return(uint8_t * arg0) {
  size_t len = *((size_t*) (arg0 + sizeof(void*)));
  if (len > 0) {
    uint8_t *ptr = *((uint8_t **) (arg0 + 0));
    for (size_t i = 0; i < len; i++) {
      uint8_t *base = ptr + i * 8;
      (void) base;
    }
    free(ptr);
  }
}


__attribute__((__weak__, __export_name__("cabi_post_local:types-test/containers#divide")))
void __wasm_export_exports_local_types_test_containers_divide_post_return(uint8_t * arg0) {
  switch ((int32_t) (int32_t) *((uint8_t*) (arg0 + 0))) {
    case 0: {
      break;
    }
    case 1: {
      if ((*((size_t*) (arg0 + (2*sizeof(void*))))) > 0) {
        free(*((uint8_t **) (arg0 + sizeof(void*))));
      }
      break;
    }
  }
}

// Exported Functions from `local:types-test/multi-params`




__attribute__((__weak__, __export_name__("cabi_post_local:types-test/multi-params#concat3")))
void __wasm_export_exports_local_types_test_multi_params_concat3_post_return(uint8_t * arg0) {
  if ((*((size_t*) (arg0 + sizeof(void*)))) > 0) {
    free(*((uint8_t **) (arg0 + 0)));
  }
}

__attribute__((__weak__, __export_name__("cabi_post_local:types-test/multi-params#mixed-params")))
void __wasm_export_exports_local_types_test_multi_params_mixed_params_post_return(uint8_t * arg0) {
  if ((*((size_t*) (arg0 + sizeof(void*)))) > 0) {
    free(*((uint8_t **) (arg0 + 0)));
  }
}

// Exported Functions from `local:types-test/side-effects`



// Canonical ABI intrinsics

__attribute__((__weak__, __export_name__("cabi_realloc")))
void *cabi_realloc(void *ptr, size_t old_size, size_t align, size_t new_size) {
  (void) old_size;
  if (new_size == 0) return (void*) align;
  void *ret = realloc(ptr, new_size);
  if (!ret) abort();
  return ret;
}

__attribute__((__aligned__(sizeof(void*))))
static uint8_t RET_AREA[(3*sizeof(void*))];

// Helper Functions

void types_test_list_s32_free(types_test_list_s32_t *ptr) {
  size_t list_len = ptr->len;
  if (list_len > 0) {
    int32_t *list_ptr = ptr->ptr;
    for (size_t i = 0; i < list_len; i++) {
    }
    free(list_ptr);
  }
}

void types_test_list_s64_free(types_test_list_s64_t *ptr) {
  size_t list_len = ptr->len;
  if (list_len > 0) {
    int64_t *list_ptr = ptr->ptr;
    for (size_t i = 0; i < list_len; i++) {
    }
    free(list_ptr);
  }
}

void types_test_list_string_free(types_test_list_string_t *ptr) {
  size_t list_len = ptr->len;
  if (list_len > 0) {
    types_test_string_t *list_ptr = ptr->ptr;
    for (size_t i = 0; i < list_len; i++) {
      types_test_string_free(&list_ptr[i]);
    }
    free(list_ptr);
  }
}

void exports_local_types_test_containers_result_s32_string_free(exports_local_types_test_containers_result_s32_string_t *ptr) {
  if (!ptr->is_err) {
  } else {
    types_test_string_free(&ptr->val.err);
  }
}

void types_test_string_set(types_test_string_t *ret, const char*s) {
  ret->ptr = (uint8_t*) s;
  ret->len = strlen(s);
}

void types_test_string_dup(types_test_string_t *ret, const char*s) {
  ret->len = strlen(s);
  ret->ptr = (uint8_t*) cabi_realloc(NULL, 0, 1, ret->len * 1);
  memcpy(ret->ptr, s, ret->len * 1);
}

void types_test_string_dup_n(types_test_string_t *ret, const char*s, size_t len) {
  ret->len = len;
  ret->ptr = (uint8_t*) cabi_realloc(NULL, 0, 1, ret->len * 1);
  memcpy(ret->ptr, s, ret->len * 1);
}

void types_test_string_free(types_test_string_t *ret) {
  if (ret->len > 0) {
    free(ret->ptr);
  }
  ret->ptr = NULL;
  ret->len = 0;
}

// Component Adapters

__attribute__((__export_name__("local:types-test/primitives#echo-s32")))
int32_t __wasm_export_exports_local_types_test_primitives_echo_s32(int32_t arg) {
  int32_t ret = exports_local_types_test_primitives_echo_s32(arg);
  return ret;
}

__attribute__((__export_name__("local:types-test/primitives#echo-s64")))
int64_t __wasm_export_exports_local_types_test_primitives_echo_s64(int64_t arg) {
  int64_t ret = exports_local_types_test_primitives_echo_s64(arg);
  return ret;
}

__attribute__((__export_name__("local:types-test/primitives#echo-f32")))
float __wasm_export_exports_local_types_test_primitives_echo_f32(float arg) {
  float ret = exports_local_types_test_primitives_echo_f32(arg);
  return ret;
}

__attribute__((__export_name__("local:types-test/primitives#echo-f64")))
double __wasm_export_exports_local_types_test_primitives_echo_f64(double arg) {
  double ret = exports_local_types_test_primitives_echo_f64(arg);
  return ret;
}

__attribute__((__export_name__("local:types-test/primitives#echo-bool")))
int32_t __wasm_export_exports_local_types_test_primitives_echo_bool(int32_t arg) {
  bool ret = exports_local_types_test_primitives_echo_bool(arg);
  return ret;
}

__attribute__((__export_name__("local:types-test/primitives#echo-string")))
uint8_t * __wasm_export_exports_local_types_test_primitives_echo_string(uint8_t * arg, size_t arg0) {
  types_test_string_t arg1 = (types_test_string_t) { (uint8_t*)(arg), (arg0) };
  types_test_string_t ret;
  exports_local_types_test_primitives_echo_string(&arg1, &ret);
  uint8_t *ptr = (uint8_t *) &RET_AREA;
  *((size_t*)(ptr + sizeof(void*))) = (ret).len;
  *((uint8_t **)(ptr + 0)) = (uint8_t *) (ret).ptr;
  return ptr;
}

__attribute__((__export_name__("local:types-test/enums#echo-color")))
int32_t __wasm_export_exports_local_types_test_enums_echo_color(int32_t arg) {
  exports_local_types_test_enums_color_t ret = exports_local_types_test_enums_echo_color(arg);
  return (int32_t) ret;
}

__attribute__((__export_name__("local:types-test/enums#color-name")))
uint8_t * __wasm_export_exports_local_types_test_enums_color_name(int32_t arg) {
  types_test_string_t ret;
  exports_local_types_test_enums_color_name(arg, &ret);
  uint8_t *ptr = (uint8_t *) &RET_AREA;
  *((size_t*)(ptr + sizeof(void*))) = (ret).len;
  *((uint8_t **)(ptr + 0)) = (uint8_t *) (ret).ptr;
  return ptr;
}

__attribute__((__export_name__("local:types-test/flags-test#echo-permissions")))
int32_t __wasm_export_exports_local_types_test_flags_test_echo_permissions(int32_t arg) {
  exports_local_types_test_flags_test_permissions_t ret = exports_local_types_test_flags_test_echo_permissions(arg);
  return ret;
}

__attribute__((__export_name__("local:types-test/flags-test#has-read")))
int32_t __wasm_export_exports_local_types_test_flags_test_has_read(int32_t arg) {
  bool ret = exports_local_types_test_flags_test_has_read(arg);
  return ret;
}

__attribute__((__export_name__("local:types-test/flags-test#has-write")))
int32_t __wasm_export_exports_local_types_test_flags_test_has_write(int32_t arg) {
  bool ret = exports_local_types_test_flags_test_has_write(arg);
  return ret;
}

__attribute__((__export_name__("local:types-test/containers#sum-list")))
int32_t __wasm_export_exports_local_types_test_containers_sum_list(uint8_t * arg, size_t arg0) {
  types_test_list_s32_t arg1 = (types_test_list_s32_t) { (int32_t*)(arg), (arg0) };
  int32_t ret = exports_local_types_test_containers_sum_list(&arg1);
  return ret;
}

__attribute__((__export_name__("local:types-test/containers#echo-list-s64")))
uint8_t * __wasm_export_exports_local_types_test_containers_echo_list_s64(uint8_t * arg, size_t arg0) {
  types_test_list_s64_t arg1 = (types_test_list_s64_t) { (int64_t*)(arg), (arg0) };
  types_test_list_s64_t ret;
  exports_local_types_test_containers_echo_list_s64(&arg1, &ret);
  uint8_t *ptr = (uint8_t *) &RET_AREA;
  *((size_t*)(ptr + sizeof(void*))) = (ret).len;
  *((uint8_t **)(ptr + 0)) = (uint8_t *) (ret).ptr;
  return ptr;
}

__attribute__((__export_name__("local:types-test/containers#count-list")))
int32_t __wasm_export_exports_local_types_test_containers_count_list(uint8_t * arg, size_t arg0) {
  types_test_list_string_t arg1 = (types_test_list_string_t) { (types_test_string_t*)(arg), (arg0) };
  int32_t ret = exports_local_types_test_containers_count_list(&arg1);
  return ret;
}

__attribute__((__export_name__("local:types-test/containers#divide")))
uint8_t * __wasm_export_exports_local_types_test_containers_divide(int32_t arg, int32_t arg0) {
  exports_local_types_test_containers_result_s32_string_t ret;
  int32_t ok;
  types_test_string_t err;
  ret.is_err = !exports_local_types_test_containers_divide(arg, arg0, &ok, &err);
  if (ret.is_err) {
    ret.val.err = err;
  }
  if (!ret.is_err) {
    ret.val.ok = ok;
  }
  uint8_t *ptr = (uint8_t *) &RET_AREA;
  if ((ret).is_err) {
    const types_test_string_t *payload1 = &(ret).val.err;*((int8_t*)(ptr + 0)) = 1;
    *((size_t*)(ptr + (2*sizeof(void*)))) = (*payload1).len;
    *((uint8_t **)(ptr + sizeof(void*))) = (uint8_t *) (*payload1).ptr;
  } else {
    const int32_t *payload = &(ret).val.ok;*((int8_t*)(ptr + 0)) = 0;
    *((int32_t*)(ptr + sizeof(void*))) = *payload;
  }
  return ptr;
}

__attribute__((__export_name__("local:types-test/multi-params#add2")))
int32_t __wasm_export_exports_local_types_test_multi_params_add2(int32_t arg, int32_t arg0) {
  int32_t ret = exports_local_types_test_multi_params_add2(arg, arg0);
  return ret;
}

__attribute__((__export_name__("local:types-test/multi-params#add3")))
int32_t __wasm_export_exports_local_types_test_multi_params_add3(int32_t arg, int32_t arg0, int32_t arg1) {
  int32_t ret = exports_local_types_test_multi_params_add3(arg, arg0, arg1);
  return ret;
}

__attribute__((__export_name__("local:types-test/multi-params#add4")))
int32_t __wasm_export_exports_local_types_test_multi_params_add4(int32_t arg, int32_t arg0, int32_t arg1, int32_t arg2) {
  int32_t ret = exports_local_types_test_multi_params_add4(arg, arg0, arg1, arg2);
  return ret;
}

__attribute__((__export_name__("local:types-test/multi-params#concat3")))
uint8_t * __wasm_export_exports_local_types_test_multi_params_concat3(uint8_t * arg, size_t arg0, uint8_t * arg1, size_t arg2, uint8_t * arg3, size_t arg4) {
  types_test_string_t arg5 = (types_test_string_t) { (uint8_t*)(arg), (arg0) };
  types_test_string_t arg6 = (types_test_string_t) { (uint8_t*)(arg1), (arg2) };
  types_test_string_t arg7 = (types_test_string_t) { (uint8_t*)(arg3), (arg4) };
  types_test_string_t ret;
  exports_local_types_test_multi_params_concat3(&arg5, &arg6, &arg7, &ret);
  uint8_t *ptr = (uint8_t *) &RET_AREA;
  *((size_t*)(ptr + sizeof(void*))) = (ret).len;
  *((uint8_t **)(ptr + 0)) = (uint8_t *) (ret).ptr;
  return ptr;
}

__attribute__((__export_name__("local:types-test/multi-params#mixed-params")))
uint8_t * __wasm_export_exports_local_types_test_multi_params_mixed_params(int32_t arg, uint8_t * arg0, size_t arg1, int32_t arg2) {
  types_test_string_t arg3 = (types_test_string_t) { (uint8_t*)(arg0), (arg1) };
  types_test_string_t ret;
  exports_local_types_test_multi_params_mixed_params(arg, &arg3, arg2, &ret);
  uint8_t *ptr = (uint8_t *) &RET_AREA;
  *((size_t*)(ptr + sizeof(void*))) = (ret).len;
  *((uint8_t **)(ptr + 0)) = (uint8_t *) (ret).ptr;
  return ptr;
}

__attribute__((__export_name__("local:types-test/side-effects#no-return")))
void __wasm_export_exports_local_types_test_side_effects_no_return(uint8_t * arg, size_t arg0) {
  types_test_string_t arg1 = (types_test_string_t) { (uint8_t*)(arg), (arg0) };
  exports_local_types_test_side_effects_no_return(&arg1);
}

__attribute__((__export_name__("local:types-test/side-effects#no-params-no-return")))
void __wasm_export_exports_local_types_test_side_effects_no_params_no_return(void) {
  exports_local_types_test_side_effects_no_params_no_return();
}

// Ensure that the *_component_type.o object is linked in

extern void __component_type_object_force_link_types_test(void);
__attribute__((used))
void __component_type_object_force_link_types_test_public_use_in_this_compilation_unit(void) {
  __component_type_object_force_link_types_test();
}
