// Generated by `wit-bindgen` 0.51.0. DO NOT EDIT!
#ifndef __BINDINGS_TYPES_TEST_H
#define __BINDINGS_TYPES_TEST_H
#ifdef __cplusplus
extern "C" {
#endif

#include <stdint.h>
#include <stdbool.h>
#include <stddef.h>

typedef struct types_test_string_t {
  uint8_t*ptr;
  size_t len;
} types_test_string_t;

// Simple enum
typedef uint8_t exports_local_types_test_enums_color_t;

#define EXPORTS_LOCAL_TYPES_TEST_ENUMS_COLOR_RED 0
#define EXPORTS_LOCAL_TYPES_TEST_ENUMS_COLOR_GREEN 1
#define EXPORTS_LOCAL_TYPES_TEST_ENUMS_COLOR_BLUE 2

// Flags type
typedef uint8_t exports_local_types_test_flags_test_permissions_t;

#define EXPORTS_LOCAL_TYPES_TEST_FLAGS_TEST_PERMISSIONS_READ (1 << 0)
#define EXPORTS_LOCAL_TYPES_TEST_FLAGS_TEST_PERMISSIONS_WRITE (1 << 1)
#define EXPORTS_LOCAL_TYPES_TEST_FLAGS_TEST_PERMISSIONS_EXECUTE (1 << 2)

typedef struct {
  int32_t *ptr;
  size_t len;
} types_test_list_s32_t;

typedef struct {
  int64_t *ptr;
  size_t len;
} types_test_list_s64_t;

typedef struct {
  types_test_string_t *ptr;
  size_t len;
} types_test_list_string_t;

typedef struct {
  bool is_err;
  union {
    int32_t ok;
    types_test_string_t err;
  } val;
} exports_local_types_test_containers_result_s32_string_t;

// Exported Functions from `local:types-test/primitives`
int32_t exports_local_types_test_primitives_echo_s32(int32_t val);
int64_t exports_local_types_test_primitives_echo_s64(int64_t val);
float exports_local_types_test_primitives_echo_f32(float val);
double exports_local_types_test_primitives_echo_f64(double val);
bool exports_local_types_test_primitives_echo_bool(bool val);
void exports_local_types_test_primitives_echo_string(types_test_string_t *val, types_test_string_t *ret);

// Exported Functions from `local:types-test/enums`
exports_local_types_test_enums_color_t exports_local_types_test_enums_echo_color(exports_local_types_test_enums_color_t c);
void exports_local_types_test_enums_color_name(exports_local_types_test_enums_color_t c, types_test_string_t *ret);

// Exported Functions from `local:types-test/flags-test`
exports_local_types_test_flags_test_permissions_t exports_local_types_test_flags_test_echo_permissions(exports_local_types_test_flags_test_permissions_t p);
bool exports_local_types_test_flags_test_has_read(exports_local_types_test_flags_test_permissions_t p);
bool exports_local_types_test_flags_test_has_write(exports_local_types_test_flags_test_permissions_t p);

// Exported Functions from `local:types-test/containers`
int32_t exports_local_types_test_containers_sum_list(types_test_list_s32_t *vals);
void exports_local_types_test_containers_echo_list_s64(types_test_list_s64_t *vals, types_test_list_s64_t *ret);
int32_t exports_local_types_test_containers_count_list(types_test_list_string_t *vals);
bool exports_local_types_test_containers_divide(int32_t a, int32_t b, int32_t *ret, types_test_string_t *err);

// Exported Functions from `local:types-test/multi-params`
int32_t exports_local_types_test_multi_params_add2(int32_t a, int32_t b);
int32_t exports_local_types_test_multi_params_add3(int32_t a, int32_t b, int32_t c);
int32_t exports_local_types_test_multi_params_add4(int32_t a, int32_t b, int32_t c, int32_t d);
void exports_local_types_test_multi_params_concat3(types_test_string_t *a, types_test_string_t *b, types_test_string_t *c, types_test_string_t *ret);
void exports_local_types_test_multi_params_mixed_params(int32_t n, types_test_string_t *s, bool b, types_test_string_t *ret);

// Exported Functions from `local:types-test/side-effects`
void exports_local_types_test_side_effects_no_return(types_test_string_t *msg);
void exports_local_types_test_side_effects_no_params_no_return(void);

// Helper Functions

void types_test_list_s32_free(types_test_list_s32_t *ptr);

void types_test_list_s64_free(types_test_list_s64_t *ptr);

void types_test_list_string_free(types_test_list_string_t *ptr);

void exports_local_types_test_containers_result_s32_string_free(exports_local_types_test_containers_result_s32_string_t *ptr);

// Sets the string `ret` to reference the input string `s` without copying it
void types_test_string_set(types_test_string_t *ret, const char*s);

// Creates a copy of the input nul-terminated string `s` and
// stores it into the component model string `ret`.
void types_test_string_dup(types_test_string_t *ret, const char*s);

// Creates a copy of the input string `s` with length `len` and
// stores it into the component model string `ret`.
// The length is specified in code units (bytes for UTF-8, 16-bit values for UTF-16).
void types_test_string_dup_n(types_test_string_t *ret, const char*s, size_t len);

// Deallocates the string pointed to by `ret`, deallocating
// the memory behind the string.
void types_test_string_free(types_test_string_t *ret);

#ifdef __cplusplus
}
#endif
#endif
